### ISSUE TITLE
Error on file opening

### ISSUE THREAD

**Issue by jaimefebe** [max-kammerer/orion-viewer#32]
[Please provide additional details and/or attach file]

Android Version: 5.1.1(22)
```
Intent { act=android.intent.action.VIEW dat=file:///storage/sdcard1/comics/01.cbz flg=0x13000000 cmp=universe.constellation.orion.viewer/.OrionViewerActivity }

java.lang.RuntimeException: cannot recognize archive
	at com.artifex.mupdf.fitz.Document.openNativeWithPath(Native Method)
	at com.artifex.mupdf.fitz.Document.openDocument(Document.java:32)
	at com.artifex.mupdf.viewer.MuPDFCore.<init>(MuPDFCore.java:35)
	at universe.constellation.orion.viewer.pdf.PdfDocument.<init>(PdfDocument.kt:34)
	at universe.constellation.orion.viewer.FileUtil.openFile(FileUtil.kt:27)
	at universe.constellation.orion.viewer.OrionViewerActivity$openFile$1$newDocument$1.invokeSuspend(OrionViewerActivity.kt:309)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by max-kammerer** [comment]
@jaimefebe Most likely there is some problem with book archive, if you can provide archive probably it can help to localize  a problem

**Comment by jaimefebe** [comment]
> @jaimefebe Most likely there is some problem with book archive, if you can provide archive probably it can help to localize a problem

Hi, unfortunately I don't remember what I was trying to open.

But thanks for your concern. :)

**Comment by max-kammerer** [comment]
I'm closing issue as obsolete
