### ISSUE TITLE
Error on file opening

### ISSUE THREAD

**Issue by boosie74** [max-kammerer/orion-viewer#35]
[Please provide additional details and/or attach file]

Android Version: 10(29)
```
Intent { act=android.intent.action.VIEW dat=content://com.lge.filemanager.FileProvider/storage/emulated/0/Download/Document.pdf typ=application/pdf flg=0x13000003 cmp=universe.constellation.orion.viewer/.OrionViewerActivity }

java.lang.RuntimeException: cannot tell in file
	at com.artifex.mupdf.fitz.Document.openNativeWithPath(Native Method)
	at com.artifex.mupdf.fitz.Document.openDocument(Document.java:32)
	at com.artifex.mupdf.viewer.MuPDFCore.<init>(MuPDFCore.java:35)
	at universe.constellation.orion.viewer.pdf.PdfDocument.<init>(PdfDocument.kt:34)
	at universe.constellation.orion.viewer.FileUtil.openFile(FileUtil.kt:27)
	at universe.constellation.orion.viewer.OrionViewerActivity$openFile$1$newDocument$1.invokeSuspend(OrionViewerActivity.kt:309)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by boosie74** [comment]
Thank you Sir
